New package for jwt
CharlyJazz/Chat-Firebase-Apache-Camel pull request #13
Opened 2022-04-03 03:25 UTC by CharlyJazz

2022-04-03 19:18 UTC, CharlyJazz commented
I created a mock for kafka in order to avoid setup a real kafka connection for just a couple of tests.

2022-04-07 00:49 UTC, aradkdj requested changes

2022-04-07 00:49 UTC, aradkdj commented on auth-microservice/Pipfile
> +auth-validator = {editable = true, path = "/Users/charlyjazz/Charlyjazz/Chat-Firebase-Apache-Camel/auth-validator"}
This won't work outside of that specific install. To make it portable you should consider using the repo as the source instead. According to [this SO answer](https://stackoverflow.com/a/19516714) it should be something like this:
```suggestion
auth-validator = {editable = true, path = "git+https://github.com/CharlyJazz/Chat-Firebase-Apache-Camel.git/#egg=pkg&subdirectory=auth-validator"}
```

2022-04-07 00:49 UTC, aradkdj commented on auth-microservice/app/tests/conftest.py
> +from typing import Dict
With python 3.9 you can subscript the built-in `dict`, no need to import it from typing
```suggestion
```

Also replace the `Dict[str, str]` on line 55 with a `dict[str, str`

2022-04-07 00:49 UTC, aradkdj commented on auth-microservice/app/tests/test_users.py
>  async def test_get_users_200(client: AsyncSession, session: AsyncConnection, user_token_headers: Dict[str, str]):
Same as above, you can subscript native `dict`, use that instead
```suggestion
from app.tests.factories import UserFactory
from app.core.config import settings

@pytest.mark.asyncio()
async def test_get_users_200(client: AsyncSession, session: AsyncConnection, user_token_headers: dict[str, str]):
```

2022-04-07 00:49 UTC, aradkdj commented on chat-microservice/app/core/config.py
> +from typing import Any, Dict, Optional
Again, no need to import `Dict` on 3.9
```suggestion
from typing import Any, Optional
```

2022-04-07 00:49 UTC, aradkdj commented on chat-microservice/app/tests/api/test_create_message_endpoint.py
> +from typing import Dict
Again, no need to import `Dict` on 3.9
```suggestion
```

2022-04-07 00:49 UTC, aradkdj commented on chat-microservice/app/tests/conftest.py
> +from typing import Dict
Again, no need to import `Dict` on 3.9
```suggestion
```

2022-04-07 00:49 UTC, aradkdj commented on chat-microservice/Pipfile
> +auth-validator = {editable = true, path = "/Users/charlyjazz/Charlyjazz/Chat-Firebase-Apache-Camel/auth-validator"}
Again, this won't work outside of that specific install. To make it portable you should consider using the repo as the source instead. According to [this SO answer](https://stackoverflow.com/a/19516714) it should be something like this:
```suggestion
auth-validator = {editable = true, path = "git+https://github.com/CharlyJazz/Chat-Firebase-Apache-Camel.git/#egg=pkg&subdirectory=auth-validator"}
```

2022-04-11 23:40 UTC, merged