issue #7 finished
CharlyJazz/Chat-Firebase-Apache-Camel pull request #23
Opened 2022-09-22 02:24 UTC by kike1996luis

-added function to deps.py to handle logging as a dependency
-added logging dependency to create message endpoint to handle logging when kafka is initialized
-added logging configuration in config.py
-added a logging class to add more features in the future if needed in the project
-added middleware to handle logs in endpoints
-added logging mock for pytest

2022-09-24 23:13 UTC, aradkdj requested changes

2022-09-24 23:13 UTC, aradkdj commented on chat-microservice/app/main.py
> +    return response
Could you refactor the middleware such that it resides in its own file in a package called “middlewares”?

2022-09-24 23:13 UTC, aradkdj commented on chat-microservice/app/main.py
> +    response.body_iterator = iterate_in_threadpool(iter(response_body))
I don't understand why do you assign `response.body_iterator` a value that you just got out of it

2022-09-25 23:12 UTC, aradkdj approved these changes
Lgtm

2022-10-02 23:13 UTC, CharlyJazz commented
This PR is ready to merge, but I going to merge it in the future.

2022-10-02 23:20 UTC, aradkdj commented
Should we mark it as draft to avoid merging it by accident?

2022-10-17 02:30 UTC, CharlyJazz commented
> Should we mark it as draft to avoid merging it by accident?

Thanks bro

2022-12-01 03:46 UTC, merged